# T-LAMP Project - @2022

openapi: 3.0.0

# General Data Model Information
info:
  title: T-LAMP Project
  description: Data model for the T-LAMP project
  version: 0.0.1
  contact:
    name: Turf Lighting Advanced Mobile Plataform Project
    url: https://tlampproject.pt/


components: 
  schemas: 

    # Definition of the Organization Entity
    Organization: 
      $ref: "https://raw.githubusercontent.com/More-Collaborative-Laboratory/TLAMP-fiware-context/main/organization.yaml#/organization"
    # Definition of the Field Entity
    Field: 
      $ref: "https://raw.githubusercontent.com/More-Collaborative-Laboratory/TLAMP-fiware-context/main/Field.yaml#/Field"
    # Definition of the Treatment Entity
    Treatment: 
      $ref: "https://raw.githubusercontent.com/More-Collaborative-Laboratory/TLAMP-fiware-context/main/Treatment.yaml#/Treatment"  
    # Definition of the Car Entity
    Car: 
      $ref: "https://raw.githubusercontent.com/More-Collaborative-Laboratory/TLAMP-fiware-context/main/Car.yaml#/Car"
    # Definition of the Channel Entity
    Channel:
      $ref: "https://raw.githubusercontent.com/More-Collaborative-Laboratory/TLAMP-fiware-context/main/Channel.yaml#/Channel"
    # Definition of Sensor Node Entity
    Sensor: 
      $ref: "https://raw.githubusercontent.com/More-Collaborative-Laboratory/TLAMP-fiware-context/main/Sensor.yaml#/Sensor"  

paths: 
  /ngsi-ld/v1/entities: 
    get: 
      responses: 
        ? "200"
        : 
          description:  OK
          content: 
            application/ld+json: 
              schema: 
                type: object
