sensor:
  title: Sensor
  type: object
  description: 'Sensor Node for T-LAMP Project.'
  properties:
    #1ยบ
    id:
      description: Sensor Node UUID
      type: string
      format: uri
      example: urn:ngsi-ld:Sensor:uuid
      x-ngsi:
        type: Property
